#+TITLE: Java One Click Run
Compile and run Java programs easily within Emacs.
* Introduction
  This is the first Emacs package I've (partialy) written. It is a simple package originated from James Borden's [[https://github.com/jborden/emacs/blob/master/java/javac.el][javac-mode]] back in 2012. There are lots of simplifications and modifications that aims to enhance the original functionality.

  It is now capable of compiling and running Java programs using one single command =java-one-click-run=. The behavior is similar to Eclipse and Intellij, which opens a shell buffer utilizing the package [[https://github.com/ieure/shell-here][shell-here]].
* Installation
  1. Clone or download this repository.
  2. Install [[https://github.com/ieure/shell-here][shell-here]].
  3. In your =~/.emacs= configuration file, add the following lines:
     #+BEGIN_SRC emacs-lisp
       (add-to-list 'load-path "<path-to-java-one-click-run>") ; add java-one-click-run to your load-path
       (require 'java-one-click-run)
     #+END_SRC
  4. Bind =java-one-click-run= to your favourite key.
  If you prefer =use-package=, a sample is provided:
  #+BEGIN_SRC emacs-lisp
    (use-package java-one-click-run
      :load-path "~/.emacs.d/site-elisp/java-one-click-run/"
      :init (use-package shell-here)
      :bind ("<f5>" . java-one-click-run))
  #+END_SRC
* Contribution
  I have never written an emacs package before, any suggestions for improvement are *very* welcomed! :)
* License
  The original package was licensed under [[https://github.com/jborden/emacs/blob/master/LICENSE][MIT]]. Now that I made this package, I decided to relicense it under [[file:LICENSE][GPLv3]] (MIT is [[https://www.gnu.org/licenses/license-list.en.html#Expat][GPL-compatible]]). Mainly to keep consistency with other emacs packages, and I like /free/ software.
